language: java
jdk: oraclejdk8
before_install: "./.travis.before_install.sh"
script: "./.travis.script.sh"
sudo: required
dist: trusty
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
before_cache:
- rm -rf $HOME/.m2/repository/com/vaadin/
- rm -rf $HOME/.ivy2/cache/com.vaadin/
env:
- secure: o4KbOyAXicOOtrxZrolaztDdi51PcXd5+lZ0/GNHLM5Q7a3cJYgIRflOpfvRJjVQAluAYJTpkLvl5EO53eZWVxh06Q6tVu6Jod/nC4Rd7ub0YBhOIcStKobHmi8S+fBcACjWizD5d0lrrgoi/lH8K7eIECROReZrIkTVlG7CYhdkQl7jbaCp+46yaLIq/feTzFB9ipTESXik2YezKURLiZa3Eh1Q6jWPJe9zpRXF/RtqrnBGkrF3ajfxNFl2HEhQRLvR/FvHrETc4wy6eP1X0+DaW+0zrsrod1G+HaO0TTGOd6cSr8n+Vuv09yONKbEHHws14YCIWIiT56pnjCRvlX8xL+Ubh/WtZ3is4KPqyHF6uP2VLoFh5TAB5Kft6t7FT1PQi91iMG6yxDJW2PrhDkERsTiiTxalz7lkNz6kR2lB9prNM9JefiEszf4BQo0cR3/T9id4jvCvNjU0zzN49N4GYCRWgs0a7skdfAGYj/d6wZ+VD29vfVDzZhwF9zFnlhImxfaPEyskMpbtofGYSTA3v/+o0BMEonhSGP9lbzSaFB6kyzTtliSIZOIY61adRpaZ7gdmw/QeuxTHf+4TXbZf1EnkVeOp7uSUZbJ/nrTzBsn27e0bAoDCSjySJDPAUyaz7ONCCXnJS8aJIFbuvifzu0DSun6Qcd1C/7vPf9k=
